# Generated by Django 5.2.7 on 2025-10-22 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)])),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('bmi', models.FloatField()),
                ('smoker', models.BooleanField(default=False)),
                ('pre_existing_conditions', models.IntegerField(default=0)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifeCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(70)])),
                ('gender', models.CharField(max_length=10)),
                ('smoker', models.BooleanField(default=False)),
                ('occupation_risk', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('policy_term', models.IntegerField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('health', 'Health Insurance'), ('life', 'Life Insurance'), ('property', 'Property Insurance'), ('vehicle', 'Vehicle Insurance')], max_length=20)),
                ('calculated_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('input_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('property_type', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('construction_year', models.IntegerField()),
                ('security_features', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('fire_safety', models.BooleanField(default=False)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_age', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('driver_age', models.IntegerField()),
                ('driver_experience', models.IntegerField()),
                ('claims_history', models.IntegerField(default=0)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
