# Generated by Django 5.2.7 on 2025-10-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_category_newsletter_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
