# Generated by Django 5.2.7 on 2025-10-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_remove_blogpost_author_remove_blogpost_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('health', 'Health Insurance'), ('vehicle', 'Vehicle Insurance'), ('life', 'Life Insurance'), ('property', 'Property Insurance'), ('tips', 'Tips & Guides')], max_length=20)),
                ('author', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('excerpt', models.TextField(max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_time', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
